#!/bin/bash

#build and run EngineTester graphics

#javac -d ./bin/main/java -cp ./bin/main/java:lib/* ./src/main/java/**/*.java &> build_log.txt -Xlint:unchecked
#java -cp ./bin/main/java:lib/* -Djava.library.path=native/linux EngineTester.MainGameLoop &>> build_log.txt -Xlint:unchecked
#xdg-open build_log.txt

#build and run EngineTester

javac -d ./bin/gui/ -cp ./bin/gui:lib/* ./src/gui/*.java -Xlint:unchecked
java -cp ./bin/gui:lib/* -Djava.library.path=native/linux Hello -Xlint:unchecked
#xdg-open build_log.txt
